FROM node:alpine

WORKDIR /app

ENV DB_LOCATION="mongodb+srv://dantulurikalyani999:0XgJDMQszefHG3xj@blogging-website-dummy.rzgoeqy.mongodb.net/?retryWrites=true&w=majority"
ENV SECRET_ACCESS_KEY="bc5d4fe813a165d012fe85d5ebad9c3a46d999fea495670aca6e271a004dfbf93767787808b773f6afea16c2db0b8bbecfff4f4ca817fc0445e5166cc55e1a26"
ENV REACT_APP_CLIENT_DOMAIN="http://localhost:3000"
ENV EMAIL="mvgrvoices@gmail.com"
ENV PASSWORD="urpj oifh lsaw fqbr"

COPY package*.json ./
RUN npm ci --only=production

# Install nodemon globally
RUN npm install -g nodemon

COPY . .

EXPOSE 3001

CMD ["nodemon", "server.js"]

