
# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email":"dantulurikalyani999@gmail.com",
#     "password":"12345"
# }

# POST http://localhost:3000/get-blog
# Content-Type: application/json

# {
#     "blog_id":"rgtrNsn6osFu_af-Q-iZ3H5gk"
# }

POST http://localhost:3000/feedback-form
Content-Type: application/json

{
    "title":"5",
    "stars":"5",
    "review":"Hello"
}
